apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: acrregistry4g9kjf.azurecr.io/backend-app:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-config
